#!/usr/bin/env bash

# clone submodules [ apache/pdfbox ]
git submodule update --init --recursive

# install the virtual environment to run python
virtualenv venv

# activate the virtual environment
source venv/bin/activate

# install all required modules
pip install -r requirements.txt

# clear screen
clear

# run the main program
python stackin.py

# de-activate the virtual environment
deactivate
